exporter:
  metrics_port: 10009 # exporter port
  scrape_timeout: 1 # scrape timeout of Prusa Link
  reload_interval: 300 # interval in seconds for config reloader
  log_level: info
printers:
  buddy:
    - address: 172.20.57.158
      username: maker
      pass: REDACTED
      name: prusa
